name: deploy-container

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: react-vue/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
