name: deploy-marketing

on:
  push:
    branches: [main]
defaults:
  run:
    working-directory: react-vue/marketing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build And Deploy
        run: npm run build
